add rights for module Client
hiqdev/hipanel-rbac pull request #16
Opened 2019-01-24 14:16 UTC by bladeroot

2019-01-30 16:42 UTC, hiqsol requested changes

2019-01-30 16:42 UTC, hiqsol commented on tests/unit/CheckAccessTrait.php
> +            'client.get-note', 'client.set-note', 'client.set-description',
задублировано

2019-01-30 16:42 UTC, hiqsol commented on tests/unit/CheckAccessTrait.php
> +            'client.get-note', 'client.set-note', 'client.set-description',
задублировано

2019-02-01 14:34 UTC, bladeroot commented on tests/unit/CheckAccessTrait.php
> +            'client.get-note', 'client.set-note', 'client.set-description',
Исправил

2019-02-01 14:46 UTC, hiqsol approved these changes

2019-02-01 14:47 UTC, merged