added generation of ts file with rbac permissions, first generated file and npm init
hiqdev/hipanel-rbac pull request #47
Opened 2021-08-12 10:30 UTC by strorch

2021-08-12 14:22 UTC, strorch commented on src/console/converter/Visitor.php
> +        }
```suggestion
        }

```

2021-08-16 16:43 UTC, SilverFire requested changes

2021-08-16 16:43 UTC, SilverFire commented on js/index.ts
> +    "RoleNobody" = "role:nobody",
```suggestion
export enum Role {
    "Nobody" = "role:nobody",
```

В ROLES_ENUM начинать ключ с Role – это масло маслянное. Я бы сделал так как выше в примере. Как думаешь?

И в JS обычно Enum'ы именуют CamelCase'ом, в едином числе и без суфикса ENUM: https://www.typescriptlang.org/docs/handbook/enums.html, потому предлагаю переименовать.

2021-08-16 16:43 UTC, SilverFire commented on js/index.ts
> +export enum PERMISSIONS_ENUM    {
```suggestion
export enum Permission {
```

2021-08-17 12:42 UTC, SilverFire approved these changes

2021-08-17 12:42 UTC, merged